var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { Overlay } from 'react-portal-overlay';
import { theme } from '../theme';
export var $Overlay = styled(Overlay)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  &.overlay {\n    display: flex;\n    background-color: ", ";\n    width: 100%;\n    padding: 30px;\n    flex-direction: column;\n  }\n"], ["\n  &.overlay {\n    display: flex;\n    background-color: ", ";\n    width: 100%;\n    padding: 30px;\n    flex-direction: column;\n  }\n"])), theme.palette.background.default);
export var $Nav = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  top: 0;\n  padding-top: 20px;\n  background-color: ", ";\n  display: flex;\n  justify-content: flex-end;\n  position: fixed;\n  width: inherit;\n  flex-direction: rows;\n\n  &.transparent {\n    background-color: transparent !important;\n  }\n\n  &.spaced {\n    justify-content: space-between !important;\n  }\n"], ["\n  top: 0;\n  padding-top: 20px;\n  background-color: ", ";\n  display: flex;\n  justify-content: flex-end;\n  position: fixed;\n  width: inherit;\n  flex-direction: rows;\n\n  &.transparent {\n    background-color: transparent !important;\n  }\n\n  &.spaced {\n    justify-content: space-between !important;\n  }\n"])), theme.palette.background.default);
export var $LogoContainer = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  color: ", ";\n  height: auto;\n  display: flex;\n  align-items: center;\n  flex-direction: row;\n"], ["\n  color: ", ";\n  height: auto;\n  display: flex;\n  align-items: center;\n  flex-direction: row;\n"])), theme.palette.greyScales[900]);
export var $Logo = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  color: ", ";\n  height: auto;\n  margin-right: 20px;\n  width: 60px;\n\n  &.blank {\n    color: #ffffff;\n  }\n\n  .big-logo {\n    font-size: 4em;\n  }\n"], ["\n  color: ", ";\n  height: auto;\n  margin-right: 20px;\n  width: 60px;\n\n  &.blank {\n    color: #ffffff;\n  }\n\n  .big-logo {\n    font-size: 4em;\n  }\n"])), theme.palette.primary);
export var $Clickable = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  color: ", ";\n  display: flex;\n  cursor: pointer;\n  align-self: center;\n\n  :hover {\n    text-decoration: underline;\n  }\n"], ["\n  color: ", ";\n  display: flex;\n  cursor: pointer;\n  align-self: center;\n\n  :hover {\n    text-decoration: underline;\n  }\n"])), theme.palette.newGreyScales[400]);
export var $Close = styled.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  font-size: 0.9em;\n  margin-right: 10px;\n  align-self: center;\n"], ["\n  font-size: 0.9em;\n  margin-right: 10px;\n  align-self: center;\n"])));
export var $Container = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  margin-top: 50px;\n  margin-bottom: 100px;\n"], ["\n  margin-top: 50px;\n  margin-bottom: 100px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
//# sourceMappingURL=overlay.styles.js.map