import { makeStyles } from '@material-ui/styles'

export default makeStyles({
  table: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    cursor: 'pointer',
    borderRadius: 4,
    backgroundColor: 'white',
    overflow: 'hidden',
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    border: 1,
    borderTopWidth: 0,
  },
  cards: {
    display: 'flex',
    flexDirection: 'column',
  },
  apiCard: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    fontWeight: 400,
    borderStyle: 'solid',
    borderTopWidth: 1,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    borderColor: '#D1D1D1',
  },
  apiCategoryContainer: {
    width: '100%',
  },
  apiTitle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    width: '60%',
    paddingLeft: 10,
    fontSize: 16,
  },
  appsListContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '40%',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#D1D1D1',
  },
  appsList: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 10,
    paddingRight: 10,
    alignItems: 'center',
  },
  avatarContainer: {
    width: 35,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: '100%',
  },
  avatar: {
    fontSize: 12,
    fontWeight: 300,
    background: 'linear-gradient(270deg, #14BC7D 0%, #14DE2D 100%)',
    width: 28,
    height: 28,
  },
  icons: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    color: '#646464',
  },
})
