import { makeStyles } from '@material-ui/styles'
import { Theme } from 'themes/types'

export default makeStyles((theme: Theme) => ({
  table: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    cursor: 'pointer',
    borderRadius: theme.shape,
    backgroundColor: 'white',
    overflow: 'hidden',
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    border: 1,
    borderTopWidth: 0,
  },
  header: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 42,
    paddingLeft: 10,
    color: '#ACACAC',
  },
  actions: {
    paddingRight: 30,
  },
  cards: {
    display: 'flex',
    flexDirection: 'column',
  },
  apiCard: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
    fontWeight: 400,
    borderStyle: 'solid',
    borderTopWidth: 1,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    borderColor: '#D1D1D1',
  },
  apiContainer: {
    width: '100%',
  },
  apiTitle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    width: '60%',
    paddingLeft: 10,
    fontSize: 16,
  },
  appsListContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '40%',
    borderStyle: 'solid',
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#D1D1D1',
  },
  appsListCardContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    minHeight: 42,
    borderStyle: 'solid',
    borderRadius: theme.shape,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#D1D1D1',
  },
  icons: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    color: '#646464',
  },
  cardContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: 438,
    width: 289,
    backgroundColor: 'white',
    borderRadius: theme.shape,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
    borderWidth: 1,
    overflow: 'hidden',
  },
  apiDetail: {
    height: '100%',
    padding: 15,
  },
  cardTitle: {
    fontSize: 22,
    margin: 0,
  },
  description: {
    fontSize: 16,
  },
  appsContainer: {
    display: 'flex',
    flexDirection: 'row',
  },
  apiVersionCard: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 14,
    width: '100%',
    height: 36,
    padding: 15,
    backgroundColor: '#EEEEEE',
    borderTopWidth: 1,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderStyle: 'solid',
    borderColor: '#D1D1D1',
  },
  viewRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
  },
  optionsContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderRadius: theme.shape,
    borderColor: '#D1D1D1',
    borderStyle: 'solid',
    cursor: 'pointer',
    overflow: 'hidden',
  },
  filter: {
    display: 'flex',
    flexDirection: 'row',
    fontSize: 16,
    fontFamily: 'inherit',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: 200,
    padding: 10,
    color: '#ACACAC',
    backgroundColor: '#EEEEEE',
    borderStyle: 'none',
  },
  icon: {
    color: '#ACACAC',
    backgroundColor: '#EEEEEE',
    height: '100%',
    cursor: 'pointer',
  },
  viewIconContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    color: '#646464',
    backgroundColor: 'white',
    borderLeftWidth: 1,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderRightWidth: 0,
    borderColor: '#D1D1D1',
    borderStyle: 'solid',
    cursor: 'pointer',
  },
  viewContainer: {
    width: '100%',
  },
  vNumber: {
    color: '#ACACAC',
  },
}))
