declare module '*.jpg'
declare module '*.jpeg'
declare module '*.png'
declare module 'react-swipeable-views-utils/lib/autoPlay'
declare module 'react-swipeable-views-utils/lib/virtualize'
declare module 'react-swipeable-views-utils/lib/bindKeyboard'
declare module 'material-ui-dots'
