import { makeStyles } from '@material-ui/styles'

export default makeStyles({
  root: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    background: 'url("../../assets/landing-bg.png") no-repeat',
    backgroundSize: '100% 100%',
    paddingTop: 300,
    paddingBottom: 45,
  },
  section: {
    maxWidth: 900,
    margin: '0 auto',
  },
  steps: {
    display: 'flex',
    flexDirection: 'row',
  },
  step: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 260,
    padding: 16,
    '& > h1': {
      width: 100,
      height: 100,
      margin: 16,
      padding: 0,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '50%',
      border: '2px solid white',
      fontSize: '48px',
      fontWeight: 300,
      color: 'white',
    },
    '& > h3': {
      width: '100%',
      margin: 16,
      padding: 0,
      fontSize: '22px',
      fontWeight: 300,
      textAlign: 'center',
      color: 'white',
    },
    '& > p': {
      textAlign: 'center',
      color: 'white',
    },
  },
  cardContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    maxWidth: 900,
    margin: '0 auto',
  },
  card: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'white',
    borderRadius: 8,
    boxShadow: '-1px -1px 1px 0px rgba(0,0,0,0.03)',
    maxWidth: 900,
    margin: '0 auto',
  },
  cardShadow: {
    position: 'absolute',
    left: 30,
    top: 'calc(100% + 5px)',
    marginTop: -4,
    transform: 'skew(45deg)',
    width: '100%',
    height: 60,
    background: 'linear-gradient(top, rgba(0,0,0,0.03) 0%, rgba(0,0,0,0) 100%)',
  },
  cardShadowSide: {
    position: 'absolute',
    right: -60,
    top: 31,
    transform: 'skewY(45deg)',
    height: '100%',
    width: 60,
    background: 'linear-gradient(left, rgba(0,0,0,0.03) 0%, rgba(0,0,0,0) 100%)',
  },
  cardRow: {
    display: 'flex',
    flexDirection: 'row',
    width: 600,
  },
  cardItem: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 300,
    height: 200,
    '& > p': {
      color: '#E3E3E3',
      textAlign: 'center',
      margin: 0,
      marginTop: 16,
    },
  },
  cardSide: {
    marginLeft: 40,
    '& > h1': {
      fontSize: '26px',
      fontWeight: 300,
    },
  },
  btn: {
    display: 'inline-block',
    color: '#333333',
    backgroundColor: 'white',
    padding: '8px 24px',
    borderRadius: 4,
    cursor: 'pointer',
    fontWeight: 500,
  },
})
